// components/FilesSection.tsx
import { DeleteButton } from "@/components/DeleteButton";
import { UploadFileButton } from "@/components/UploadFileButton";
import fs from "fs";
import { Cell } from "./Cell";

export function FilesSection({ className = "" }: { className?: string }) {
  const files = fs.readdirSync("./tmp/files/");
  const hasFiles = files.length > 0;

  return (
    <div className={`w-full flex flex-col items-center ${className}`}>
      <h2 className="text-3xl">Files</h2>
      {hasFiles && (
        <table className="mt-4 w-full md:w-fit">
          <tbody>
            {files.map((fileName) => (
              <tr key={fileName}>
                <Cell className="w-full whitespace-pre-line overflow-auto">
                  <a
                    className="underline"
                    href={`/api/files/${fileName}`}
                    download
                  >
                    {fileName}
                  </a>
                </Cell>
                <Cell>
                  <DeleteButton type="file" id={fileName} />
                </Cell>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      <div className="pt-4 flex gap-2">
        <UploadFileButton />
        {hasFiles && <DeleteButton type="file" all />}
      </div>
    </div>
  );
}

// src/lib/FilesSection.svelte
<script lang="ts">
	import DeleteButton from './DeleteButton.svelte';
	import UploadFileButton from './UploadFileButton.svelte';

	type FilesSectionProps = {
		classes?: string;
		files: {
			id: string;
			name: string;
			link: string;
		}[];
	};

	let { classes, files }: FilesSectionProps = $props();
	let hasFiles = $derived(files.length > 0);
</script>

<div class={`w-full ${classes}`}>
	<h2 class="mx-auto w-fit text-3xl">Files</h2>
	{#if hasFiles}
		<div class="mt-4 flex w-full flex-col gap-1">
			{#each files as { id, name, link } (name)}
				<div class="flex w-full items-center gap-2 border-2 p-2">
					<div class="grow">
						<a class="underline" href={link} download>
							{name}
						</a>
					</div>
					<DeleteButton type="file" {id} />
				</div>
			{/each}
		</div>
	{/if}
	<div class="mx-auto flex items-center justify-center gap-2 pt-4">
		<UploadFileButton />
		{#if hasFiles}
			<DeleteButton type="file" />
		{/if}
	</div>
</div>
