// src/lib/DeleteButton.svelte
<script lang="ts">
	import { invalidate } from '$app/navigation';
	import Button from './Button.svelte';

	let {
		type,
		id = undefined
	}: {
		type: 'file' | 'text';
		id?: string;
	} = $props();

	async function handleClick() {
		let url =
			type === 'file'
				? id
					? `/api/files/${id}`
					: `/api/files`
				: id
					? `/api/text/${id}`
					: `/api/text`;

		await fetch(url, { method: 'DELETE' });
		invalidate('app:load-text-files');
	}
</script>

<Button color="red" icon={{ src: '/bin.svg', alt: 'Trash bin' }} onClick={handleClick} />

// components/DeleteButton.tsx
"use client";

import { Button } from "./Button";
import { useRouter } from "next/navigation";

type DeleteButtonProps = {
  type: "file" | "text";
  all?: boolean;
  id?: string;
};

export function DeleteButton({ type, all = false, id }: DeleteButtonProps) {
  const router = useRouter();

  async function handleClick() {
    if (type === "file") {
      if (all) {
        await fetch(`/api/files`, { method: "DELETE" });
      } else {
        await fetch(`/api/files/${id}`, { method: "DELETE" });
      }
    } else {
      if (all) {
        await fetch(`/api/text`, { method: "DELETE" });
      } else {
        await fetch(`/api/text/${id}`, { method: "DELETE" });
      }
    }

    router.refresh();
  }

  return (
    <Button
      color="red"
      icon={{ src: "/bin.svg", alt: "Trash bin" }}
      onClick={handleClick}
    />
  );
}
