// src/lib/TextSection.svelte
<script lang="ts">
	import CopyTextButton from './CopyTextButton.svelte';
	import DeleteButton from './DeleteButton.svelte';
	import TextForm from './TextForm.svelte';

	type TextSectionProps = { texts: { id: string; isLink: boolean; contents: string }[] };

	let { texts }: TextSectionProps = $props();
	let hasTexts = $derived(texts.length > 0);
</script>

<div class="w-full">
	<h2 class="mx-auto w-fit text-3xl">Text</h2>
	{#if hasTexts}
		<div class="mt-4 flex w-full flex-col gap-1">
			{#each texts as { id, isLink, contents } (id)}
				<div class="flex w-full items-center gap-2 border-2 p-2">
					<div class="grow break-all">
						{#if isLink}
							<a class="underline" href={contents}>
								{contents}
							</a>
						{:else}
							{contents}
						{/if}
					</div>
					<CopyTextButton text={contents} />
					<DeleteButton type="text" {id} />
				</div>
			{/each}
		</div>
	{/if}
	<div class="mx-auto flex justify-center gap-2 pt-4">
		<TextForm />
		{#if hasTexts}
			<DeleteButton type="text" />
		{/if}
	</div>
</div>

// components/TextSection.tsx
import { CopyTextButton } from "@/components/CopyTextButton";
import { DeleteButton } from "@/components/DeleteButton";
import fs from "fs";
import { Cell } from "./Cell";
import { TextForm } from "./TextForm";

export function TextSection({ className = "" }: { className?: string }) {
  // TODO: Think about using websockets to refresh?
  const fileNames = fs.readdirSync("./tmp/text/");
  const hasFiles = fileNames.length > 0;

  const fileContents = fileNames.map((fileName) => {
    // Adding an empty string will convert Buffer to string
    const contents = "" + fs.readFileSync(`./tmp/text/${fileName}`);
    return {
      id: fileName,
      isLink: /^(https?:\/\/[^\s]+)$/.test(contents),
      contents: contents,
    };
  });

  return (
    <div className={`w-full flex flex-col items-center ${className}`}>
      <h2 className="text-3xl">Text</h2>
      {hasFiles && (
        <table className="mt-4 w-full md:w-fit">
          <tbody>
            {fileContents.map(({ id, isLink, contents }) => (
              <tr key={id}>
                <Cell className="w-full whitespace-pre-line overflow-auto">
                  {isLink ? (
                    <a className="underline" href={contents}>
                      {contents}
                    </a>
                  ) : (
                    contents
                  )}
                </Cell>
                <Cell>
                  <CopyTextButton text={contents} />
                </Cell>
                <Cell>
                  <DeleteButton type="text" id={id} />
                </Cell>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      <div className="pt-4 flex gap-2">
        <TextForm />
        {hasFiles && <DeleteButton type="text" all />}
      </div>
    </div>
  );
}
