// src/lib/UploadFileButton.svelte
<script lang="ts">
	import { invalidate } from '$app/navigation';
	import type { ChangeEventHandler } from 'svelte/elements';

	let numFilesUploaded: number | undefined = $state();
	let numTotalFiles: number | undefined = $state();

	const onchange: ChangeEventHandler<HTMLInputElement> = async (event) => {
		const { files } = event.currentTarget;
		if (!files) return;

		numFilesUploaded = 0;
		numTotalFiles = files.length;

		for (const file of files) {
			const formData = new FormData();
			formData.append('file', file);

			await fetch('/api/files', {
				method: 'POST',
				body: formData
			});

			numFilesUploaded++;
		}

		numFilesUploaded = undefined;
		numTotalFiles = undefined;
		invalidate('app:load-text-files');
	};
</script>

{#if numFilesUploaded === undefined}
	<input type="file" id="upload-button" hidden multiple {onchange} />
	<label
		for="upload-button"
		class="flex w-32 cursor-pointer items-center justify-center bg-blue-500 px-4 py-2 text-slate-100 active:bg-blue-600"
	>
		<img
			class="min-h-6 min-w-6"
			color="#fff"
			src="/upload.svg"
			alt="Upload symbol"
			width="24"
			height="24"
		/>
	</label>
{:else}
	<div class="px-6 text-center text-slate-500">
		Uploading: {numFilesUploaded + 1}/{numTotalFiles}
	</div>
{/if}

// components/UploadFileButton.tsx
"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { ChangeEvent, useState } from "react";

type UploadState = {
  done: number;
  total: number;
};

export function UploadFileButton({ className = "" }: { className?: string }) {
  const [uploadState, setUploadState] = useState<UploadState | null>(null);
  const router = useRouter();

  async function handleChange(e: ChangeEvent<HTMLInputElement>) {
    const selectedFiles = e.target.files;

    if (!selectedFiles) {
      return;
    }

    for (let i = 0; i < selectedFiles.length; i++) {
      setUploadState({ done: i, total: selectedFiles.length });
      const formData = new FormData();
      formData.append("file", selectedFiles[i]);

      await fetch("/api/files", {
        method: "POST",
        body: formData,
      });
    }

    setUploadState(null);
    router.refresh();
  }

  if (uploadState) {
    return (
      <div className="w-full text-center text-slate-500">
        {`Uploading: ${uploadState.done + 1}/${uploadState.total}`}
      </div>
    );
  }

  return (
    <div className={className}>
      <input
        type="file"
        id="upload-button"
        hidden
        multiple
        onChange={handleChange}
      />
      <label
        htmlFor="upload-button"
        className="px-6 py-3 flex items-center justify-center bg-blue-500 active:bg-blue-600 text-slate-100 cursor-pointer"
      >
        <Image
          className="min-h-4 min-w-4"
          color="#fff"
          src="/upload.svg"
          alt="Upload symbol"
          width="24"
          height="24"
        />
      </label>
    </div>
  );
}
